export const enum MERGE_STATUS {
  ACCEPTED = 'ACCEPTED',
  REFUSED = 'REFUSED',
  CANMERGE = 'CANMERGE',
  CANNOTMERGE = 'CANNOTMERGE'
}

export const MERGE_STATUS_TEXT = {
  [MERGE_STATUS.ACCEPTED]: '已合并',
  [MERGE_STATUS.CANMERGE]: '可合并',
  [MERGE_STATUS.REFUSED]: '已关闭',
  [MERGE_STATUS.CANNOTMERGE]: '不可自动合并'
};
